csharpRepos/StockAppWeb/Models/BaseEntity.cs
using System;

namespace StockAppWeb.Models
{
    public class BaseEntity
    {
        public int Id { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}

csharpRepos/StockAppWeb/Models/Category.cs
using System;

namespace StockAppWeb.Models
{
    public class Category : BaseEntity
    {
        public string Name { get; set; }
        public Category(int id, string name, DateTime created_at)
        {
            Id = id;
            Name = name;
            CreatedAt = created_at;
        }

        public override string ToString()
        {
            return $"{Id}\t{Name}\t{CreatedAt}";
        }
    }
}

csharpRepos/StockAppWeb/Models/ErrorViewModel.cs
using System;

namespace StockAppWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

csharpRepos/StockAppWeb/Models/Stock.cs
using System;

namespace StockAppWeb.Models
{
    public class Stock : BaseEntity
    {
        public int Category_Id;
        public string Category { get; set; }
        public string Brand { get; set;}
        public string Name { get; set; }
        public double CostPrice { get; set; }
        public double SellingPrice { get; set; }
        public string SKU { get; set; }
        public int Quantity { get; set; }
        public string Variation { get; set; }

        public Stock(int id, string brand, string name, double costPrice, double sellingPrice, string sKU, int quantity, string variation, DateTime created_at, int category_Id)
        {
            Id = id;
            CreatedAt = created_at;
            Brand = brand;
            Name = name;
            CostPrice = costPrice;
            SellingPrice = sellingPrice;
            SKU = sKU;
            Quantity = quantity;
            Variation = variation;
            Category_Id = category_Id;
        }

        public Stock(int id, string brand, string name, double costPrice, double sellingPrice, string sku, int quantity, DateTime created_at, string category)
        {
            Id = id;
            Brand = brand;
            Name = name;
            CostPrice = costPrice;
            SellingPrice = sellingPrice;
            SKU = sku;
            Quantity = quantity;
            CreatedAt = created_at;
            Category = category;
        }

        public override string ToString()
        {
            return $"{Id}\t{CreatedAt}\t{Brand}\t{Name}\t{CostPrice}\t{SellingPrice}\t{SKU}\t{Quantity}\t{Variation}\t{Category_Id}";
        }
    }
}

csharpRepos/StockAppWeb/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using StockAppWeb.Repositories;
using System;

namespace StockApplication.Controllers
{
    public class CategoryController : Controller
    {
        static string connectionString = "server=localhost;user=root;database=stockmanagement;port=3306;password=419300";
        static MySqlConnection conn = new MySqlConnection(connectionString);

        CategoryRepository categoryRepo = new CategoryRepository(conn);

        public IActionResult Index()
        {
            var categoryList = categoryRepo.ListAllCategories();

            return View(categoryList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Create(int id, string name)
        {
            DateTime created_at = DateTime.Now;
            categoryRepo.AddCategory(id, name, created_at);
            //return View();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var category = categoryRepo.FindCategory(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        public IActionResult Update(int id)

        {
            var category = categoryRepo.FindCategory(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);

        }
        [HttpPost]
        public IActionResult Update(int id, string name)
        {
            categoryRepo.UpdateCategory(id, name);
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        {
            var category = categoryRepo.FindCategory(id);
            if (category == null)
            {
                return NotFound();
            }
 
            categoryRepo.DeleteCategory(id);
            return RedirectToAction("Index");
        }

    }
}

csharpRepos/StockAppWeb/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MySql.Data.MySqlClient;
using StockAppWeb.Models;
using StockAppWeb.Repositories;

namespace StockAppWeb.Controllers
{
        public class HomeController : Controller
    {
        static string connectionString = "server=localhost;user=root;database=stockmanagement;port=3306;password=419300";
        static MySqlConnection conn = new MySqlConnection(connectionString);
        CategoryRepository categoryRepo = new CategoryRepository(conn);

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
         
            var categoryList = categoryRepo.ListLatestCategories();

            return View(categoryList);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

csharpRepos/StockAppWeb/Controllers/StockController.cs
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using StockAppWeb.Repositories;
using System;
// using System.Collections.Generic;
// using System.Linq;
// using System.Threading.Tasks;

namespace StockApplication.Controllers
{
    public class StockController : Controller
    {
       
        static string connectionString = "server=localhost;user=root;database=stockmanagement;port=3306;password=419300";
        static MySqlConnection conn = new MySqlConnection(connectionString);

        StockRepository stockRepository = new StockRepository(conn);

        CategoryRepository categoryRepository = new CategoryRepository(conn);

        public IActionResult Index()
        {
            var stockList = stockRepository.ListAllStocks();

            return View(stockList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var category = categoryRepository.ListAllCategories();

            return View(category);
        }

        [HttpPost]

        public IActionResult Create(int id,string brand, string name, double costPrice, double sellingPrice, string sKU, int quantity, string variation, int category_Id)
        {
            DateTime created_at = DateTime.Now;
            stockRepository.AddStock(id, brand, name, costPrice, sellingPrice, sKU, quantity, variation, created_at, category_Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var stock = stockRepository.FindStock(id);
            if (stock == null)
            {
                return NotFound();
            }
            return View(stock);
        }

        public IActionResult Update(int id)

        {
            var stock = stockRepository.FindStock(id);
            if (stock == null)
            {
                return NotFound();
            }
            return View(stock);

        }
        [HttpPost]
        public IActionResult Update(int id, string brand, string name, double costPrice, double sellingPrice, string sKU, int quantity, string variation)
        {
            stockRepository.UpdateStock(id, brand, name, costPrice, sellingPrice, sKU, quantity, variation);
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        {
            var stock = stockRepository.FindStock(id);
            if (stock == null)
            {
                return NotFound();
            }

            stockRepository.DeleteStock(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Expensive()
        {
            var expensiveList = stockRepository.ListExpensiveStocks();

            return View(expensiveList);
        }
    }
    
}

csharpRepos/StockAppWeb/Views/Category/Create.cshtml
  
@{
    ViewData["Title"] = "Create Category";
}

<h1>Create Category</h1>

<section class="row mb-3">
    <div class="col-4">
        <form method="post"><br>
           <input type="text" name="name" placeholder="Enter Category Name " class="form-control"/> <br>
           <input type="submit" value="Create Category" class="btn btn-primary"/> 
        </form>
   </div>
</section>

csharpRepos/StockAppWeb/Views/Category/Delete.cshtml
@{
    ViewData["Title"] = "Delete Category";
}

<h1>Delete Category</h1>

<form method="post">
    <input type="text" name="id" placeholder="Enter Category Id you want to delete "class="form-control"/>
 
    <input type="submit" value="DeleteCategory"class="btn btn-primary" />
</form>

csharpRepos/StockAppWeb/Views/Category/Detail.cshtml
@model Category

@{ 
    ViewData["Title"] = "Category Detail";
}

<ul>
    <li>Id: @Model.Id</li>
    <li>Name: @Model.Name</li>
    <li>Created At: @Model.CreatedAt</li>
</ul>
<div>
        <a class="btn btn-success" asp-controller="Category" asp-action="Index">Back to Category</a>
</div> 

csharpRepos/StockAppWeb/Views/Category/Index.cshtml
@model List<Category>

@{
    ViewData["Title"] = "Category";
}

<div class="card">
    <div class="card-header">
        <a class="btn btn-success" asp-controller="Category" asp-action="Create">Add Category</a>
    </div>

    <div class="card-body">
        <table class="table table-bordered table-striped">
            <thead>
                <tr style="color:green">
                    <th>Id</th>
                    <th>Name</th>
                    <th>CreatedAt</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Category category in Model)
                {
                    <tr style="color:green">
                        <td>@category.Id</td>
                        <td>@category.Name</td>
                        <td>@category.CreatedAt</td>
                        <td>
                            <a class="btn btn-primary" asp-action="Detail" asp-route-id="@category.Id">View Category</a>
                            <a class="btn btn-success" asp-action="Update" asp-route-id="@category.Id">Update Category</a>
                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@category.Id">Delete Category</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

csharpRepos/StockAppWeb/Views/Category/Update.cshtml
@model Category
<h1>Update Category</h1>
<form method="post">
    <input type="hidden" name="id" value="@Model.Id"/>
    <label>Name:.</label><input name="name" value="@Model.Name" type="text"/><br><br>
    <div>
        <button class="btn btn-success" type="submit">Update</button>
    </div>
</form>

csharpRepos/StockAppWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Category";
}

<div class="card">
    <div class="card-header">
        <h1 class="text-center" style="color: green">Latest Categories</h1>
        <a class="btn btn-success" asp-controller="Category" asp-action="Index">Go to Category</a>
    </div>

    <div class="card-body">
        <table class="table table-bordered table-striped">
            <thead>
                <tr style="color:green">
                    <th >Id</th>
                    <th>Name</th>
                    <th>CreatedAt</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Category category in Model)
                {
                    <tr style="color:green">
                        <td>@category.Id</td>
                        <td>@category.Name</td>
                        <td>@category.CreatedAt</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

csharpRepos/StockAppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StockApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StockApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stock" asp-action="Index">Stock</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - StockApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>